server:
  forward-headers-strategy: framework
spring:
  application:
    name: coupon
  datasource:
    url: jdbc:postgresql://localhost:5432/coupons
    username: coupons
    password: coupons
  flyway:
    enabled: true
    jpa:
      hibernate:
        ddl-auto: validate

management:
  otlp:
    metrics:
      export:
        enabled: false
